# How to create a 1D array?
Difficulty Level: L1

Q. Create a 1D array of numbers from 0 to 9

Desired output:

#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
import numpy as np

In [9]:
x = np.arange(0,10)

In [4]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
a = [0,1,2,3,4,5,6,7,8,9]

In [12]:
aa = np.array(a)

In [13]:
aa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# How to reshape an array?
Difficulty Level: L1

Q. Convert a 1D array to a 2D array with 2 rows

Input:

np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

In [14]:
b = np.arange(10)

In [15]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
bb = np.reshape(b)(2,5)

TypeError: reshape() missing 1 required positional argument: 'newshape'

In [20]:
b.reshape(2,5)  
#arr.reshape(2, -1) setting to -1 automatically decide the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# How to replace items that satisfy a condition without affecting the original array?

Difficulty Level: L2

Q. Replace all odd numbers in arr with -1 without changing arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:

out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

arr

#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr2 = arr.flatten()

In [30]:
arr2 = arr(0,10,1) -1

TypeError: 'numpy.ndarray' object is not callable

In [32]:
arr = np.arange(10)

In [33]:
out = np.where(arr % 2 == 1, -1, arr)

In [34]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# How to remove from one array those items that exist in another?
Difficulty Level: L2

Q. From array a remove all items present in array b

Input:

a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])

Desired Output:

array([1,2,3,4])

In [42]:
a = np.arange(1,6)

In [43]:
b = np.arange(5,10)

In [44]:
print(a, b)

[1 2 3 4 5] [5 6 7 8 9]


In [45]:
a

array([1, 2, 3, 4, 5])

In [46]:
b

array([5, 6, 7, 8, 9])

In [47]:
# From "a" remove all of "b"
np.setdiff1d(a, b)

array([1, 2, 3, 4])

# How to filter a numpy array based on two or more conditions?
Difficulty Level: L3

Q. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

## Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


## Solution

In [49]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


condition = (iris_2d[:, 2]> 1.5) & (iris_2d[:, 0]< 5.0)

In [50]:
iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

# How to create row numbers grouped by a categorical variable?
Difficulty Level: L3

Q. Create row numbers grouped by a categorical variable. Use the following sample from iris species as input.

Input:

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)

species_small = np.sort(np.random.choice(species, size=20))

species_small

Desired Output:

#> [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7]

In [65]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)

np.random.seed(100)

species_small = np.sort(np.random.choice(species, size=20))

species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica'], dtype='<U15')

In [66]:
print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5]


# How to find all the local maxima (or peaks) in a 1d array?
Difficulty Level: L4

Q. Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

Input:

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

Desired Output:

#> array([2, 5])

where, 2 and 5 are the positions of peak values 7 and 6.

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

In [69]:
aa = np.where(a > 5)

In [70]:
aa

(array([2, 5], dtype=int64),)

## Solution

In [71]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations

array([2, 5], dtype=int64)

# How to create strides from a given 1D array?
Difficulty Level: L4

Q. From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

Input:

arr = np.arange(15) 

arr

#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Desired Output:

#> [[ 0  1  2  3]
#>  [ 2  3  4  5]
#>  [ 4  5  6  7]
#>  [ 6  7  8  9]
#>  [ 8  9 10 11]
#>  [10 11 12 13]]

arr = np.arange(15)

arr

In [76]:
arr.strides(4,2)

TypeError: 'tuple' object is not callable

## Solutions

In [79]:
def gen_strides(a, stride_len = 5, window_len = 5):
    n_strides = ((a.size - window_len)// stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, n_strides*stride_len, stride_len)])

In [80]:
print(gen_strides(np.arange(15), stride_len=2, window_len=4))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
